name: liquidglass_light
description: A high-performance Flutter package that creates liquid, glass-like borders with gyro-simulated light reflections and dynamic gradients.
version: 0.0.3
homepage: https://github.com/arihantsingh04/liquidglass_light/
repository: https://github.com/arihantsingh04/liquidglass_light/
issue_tracker: https://github.com/arihantsingh04/liquidglass_light/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.0.0 # Updated to latest stable

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: